# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '15.1'
prepare_react_native_project!
use_modular_headers!

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'Searchkro' do
  config = use_native_modules!
  use_frameworks! :linkage => :static

  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Messaging'

  # Add this to resolve Firebase static library issues
  pod 'Firebase/Core', :modular_headers => true
  pod 'Firebase/Auth', :modular_headers => true
  pod 'Firebase/Firestore', :modular_headers => true
  pod 'Firebase/Messaging', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  pod 'FirebaseCoreExtension', :modular_headers => true
  pod 'RecaptchaInterop', :modular_headers => true
 
  new_arch_enabled = true
  # React Native dependencies
  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => false, # Enable Hermes (recommended)
    :fabric_enabled => new_arch_enabled, # Enable Fabric
    :new_arch_enabled => new_arch_enabled # Enable TurboModules
  )

  target 'SearchkroTests' do
    inherit! :complete
  end
end